using System;
using System.Collections.Generic;

#nullable disable

namespace APINosis.Entities
{
    public partial class Grccbh
    {
        public string Grccbh_Modcom { get; set; }
        public string Grccbh_Codcom { get; set; }
        public string Grccbh_Descrp { get; set; }
        public string Grccbh_Titulo { get; set; }
        public string Grccbh_Tipreg { get; set; }
        public string Grccbh_Stmascar { get; set; }
        public string Grccbh_Sttipmov { get; set; }
        public string Grccbh_Stregdes { get; set; }
        public string Grccbh_Sttipcue { get; set; }
        public string Grccbh_Stdeposi { get; set; }
        public string Grccbh_Stsector { get; set; }
        public string Grccbh_Stdephas { get; set; }
        public string Grccbh_Stsechas { get; set; }
        public string Grccbh_Textos { get; set; }
        public string Grccbh_Cgmascar { get; set; }
        public string Grccbh_Cgsubdia { get; set; }
        public string Grccbh_Cgtipmov { get; set; }
        public string Grccbh_Cjclasif { get; set; }
        public string Grccbh_Cjmodasi { get; set; }
        public string Grccbh_Cjcodasi { get; set; }
        public string Grccbh_Cjcodcaj { get; set; }
        public string Grccbh_Cjdefitm { get; set; }
        public string Grccbh_Cjvalcta { get; set; }
        public string Grccbh_Comascar { get; set; }
        public string Grccbh_Fcmascar { get; set; }
        public string Grccbh_Pvmodasi { get; set; }
        public string Grccbh_Pvcodasi { get; set; }
        public string Grccbh_Pvcoltot { get; set; }
        public string Grccbh_Pvimptcn { get; set; }
        public string Grccbh_Pvincest { get; set; }
        public string Grccbh_Pvinciti { get; set; }
        public string Grccbh_Pvincsel { get; set; }
        public string Grccbh_Pvrelaci { get; set; }
        public string Grccbh_Pvsigtot { get; set; }
        public string Grccbh_Pvsubdia { get; set; }
        public string Grccbh_Vtmodasi { get; set; }
        public string Grccbh_Vtcodasi { get; set; }
        public string Grccbh_Vtcoltot { get; set; }
        public string Grccbh_Vtimptcn { get; set; }
        public string Grccbh_Vtincvnd { get; set; }
        public string Grccbh_Vtinccob { get; set; }
        public string Grccbh_Vtincest { get; set; }
        public string Grccbh_Vtinciti { get; set; }
        public string Grccbh_Vtrelaci { get; set; }
        public string Grccbh_Vtsigtot { get; set; }
        public string Grccbh_Vtsubdia { get; set; }
        public string Grccbh_Vtexport { get; set; }
        public string Grccbh_Cftipesm { get; set; }
        public string Grccbh_Vtvalrec { get; set; }
        public string Grccbh_Cgdimuni { get; set; }
        public string Grccbh_Cjdimuni { get; set; }
        public string Grccbh_Vtdimuni { get; set; }
        public string Grccbh_Pvdimuni { get; set; }
        public string Grccbh_Sjdimuni { get; set; }
        public string Grccbh_Stdimuni { get; set; }
        public string Grccbh_Vtincvta { get; set; }
        public string Grccbh_Cjincsub { get; set; }
        public string Grccbh_Pvvalrec { get; set; }
        public short? Grccbh_Copias { get; set; }
        public string Grccbh_Cjsubdia { get; set; }
        public string Grccbh_Recfec { get; set; }
        public string Grccbh_Cvtipcom { get; set; }
        public string Grccbh_Cbctacte { get; set; }
        public string Grccbh_Pvincpvs { get; set; }
        public string Grccbh_Hserie { get; set; }
        public string Grccbh_Hdespa { get; set; }
        public string Grccbh_Hotros { get; set; }
        public string Grccbh_Henvas { get; set; }
        public string Grccbh_Hfecha { get; set; }
        public string Grccbh_Hatrib { get; set; }
        public string Grccbh_Hestan { get; set; }
        public string Grccbh_Hubica { get; set; }
        public string Grccbh_Cfvenc { get; set; }
        public string Grccbh_Pdnroint { get; set; }
        public string Grccbh_Sjtipcom { get; set; }
        public string Grccbh_Sjcodcpt { get; set; }
        public string Grccbh_Stmodasi { get; set; }
        public string Grccbh_Stcodasi { get; set; }
        public string Grccbh_Cjcierre { get; set; }
        public string Grccbh_Stclasif { get; set; }
        public string Grccbh_Fcincest { get; set; }
        public string Grccbh_Coincest { get; set; }
        public string Grccbh_Gcfchmov { get; set; }
        public string Grccbh_Cjlector { get; set; }
        public string Grccbh_Cgcoflis { get; set; }
        public string Grccbh_Cgedimon { get; set; }
        public string Grccbh_Tipcom { get; set; }
        public string Grccbh_Mulfrm { get; set; }
        public string Grccbh_Defstd { get; set; }
        public string Grccbh_Trafcr { get; set; }
        public string Grccbh_Modcdv { get; set; }
        public string Grccbh_Codcdv { get; set; }
        public string Grccbh_Vtnoapli { get; set; }
        public string Grccbh_Pvnoapli { get; set; }
        public string Grccbh_Vtmoddeb { get; set; }
        public string Grccbh_Vtcomdeb { get; set; }
        public string Grccbh_Vtmoddebc { get; set; }
        public string Grccbh_Vtcomdebc { get; set; }
        public string Grccbh_Vtmodcre { get; set; }
        public string Grccbh_Vtcomcre { get; set; }
        public string Grccbh_Vtmodcrec { get; set; }
        public string Grccbh_Vtcomcrec { get; set; }
        public string Grccbh_Pvmoddeb { get; set; }
        public string Grccbh_Pvcomdeb { get; set; }
        public string Grccbh_Pvmoddebc { get; set; }
        public string Grccbh_Pvcomdebc { get; set; }
        public string Grccbh_Pvmodcre { get; set; }
        public string Grccbh_Pvcomcre { get; set; }
        public string Grccbh_Pvmodcrec { get; set; }
        public string Grccbh_Pvcomcrec { get; set; }
        public string Grccbh_Vtmodanu { get; set; }
        public string Grccbh_Vtcomanu { get; set; }
        public string Grccbh_Vtmodanuc { get; set; }
        public string Grccbh_Vtcomanuc { get; set; }
        public string Grccbh_Pvmodanu { get; set; }
        public string Grccbh_Pvcomanu { get; set; }
        public string Grccbh_Pvmodanuc { get; set; }
        public string Grccbh_Pvcomanuc { get; set; }
        public string Grccbh_Cjtrafch { get; set; }
        public DateTime? Grccbh_Cjfchdes { get; set; }
        public string Grccbh_Cvmascar { get; set; }
        public string Grccbh_Pveditimp { get; set; }
        public string Grccbh_Cbinfche { get; set; }
        public string Grccbh_Pvcodsem { get; set; }
        public string Grccbh_Pvnoauto { get; set; }
        public string Grccbh_Lector { get; set; }
        public string Grccbh_Stllepla { get; set; }
        public decimal? Grccbh_Vtpormin { get; set; }
        public decimal? Grccbh_Vtpormax { get; set; }
        public decimal? Grccbh_Pvpormin { get; set; }
        public decimal? Grccbh_Pvpormax { get; set; }
        public string Grccbh_Vtindbcr { get; set; }
        public string Grccbh_Vtnodif { get; set; }
        public string Grccbh_Pvnodif { get; set; }
        public string Grccbh_Coddim { get; set; }
        public string Grccbh_Subcue { get; set; }
        public string Grccbh_Pvctactr { get; set; }
        public string Grccbh_Reppre { get; set; }
        public string Grccbh_Noreci { get; set; }
        public string Grccbh_Condia { get; set; }
        public string Grccbh_Pvfiscal { get; set; }
        public string Grccbh_Stvalxcr { get; set; }
        public string Grccbh_Person { get; set; }
        public string Grccbh_Modnum { get; set; }
        public string Grccbh_Modfec { get; set; }
        public string Grccbh_Secnum { get; set; }
        public string Grccbh_Secfec { get; set; }
        public string Grccbh_Repece { get; set; }
        public string Grccbh_Vtincpvs { get; set; }
        public string Grccbh_Pvincvta { get; set; }
        public string Grccbh_Cjreqcob { get; set; }
        public string Grccbh_Gpclasif { get; set; }
        public string Grccbh_Cbnrocta { get; set; }
        public string Grccbh_Gpsaveal { get; set; }
        public string Grccbh_Ideven { get; set; }
        public short? Grccbh_Cntadc { get; set; }
        public short? Grccbh_Estaut { get; set; }
        public string Grccbh_Manulp { get; set; }
        public string Grccbh_Canulp { get; set; }
        public short? Grccbh_Estrec { get; set; }
        public string Grccbh_Vteditimp { get; set; }
        public DateTime? Grccbh_Fecalt { get; set; }
        public DateTime? Grccbh_Fecmod { get; set; }
        public string Grccbh_Userid { get; set; }
        public string Grccbh_Ultopr { get; set; }
        public string Grccbh_Debaja { get; set; }
        public string Grccbh_Oalias { get; set; }
    }
}
