using System;
using System.Collections.Generic;

#nullable disable

namespace APINosis.Entities
{
    public partial class Vtmclh
    {
        public string VtmclhNrocta { get; set; }
        public string VtmclhRubr01 { get; set; }
        public string VtmclhRubr03 { get; set; }
        public string VtmclhRubr04 { get; set; }
        public string VtmclhRubr05 { get; set; }
        public string VtmclhRubr06 { get; set; }
        public string VtmclhRubr07 { get; set; }
        public string VtmclhRubr08 { get; set; }
        public string VtmclhRubr09 { get; set; }
        public string VtmclhRubr10 { get; set; }
        public string VtmclhRubr02 { get; set; }
        public string VtmclhNombre { get; set; }
        public string VtmclhNrosub { get; set; }
        public string VtmclhRespon { get; set; }
        public string VtmclhDirecc { get; set; }
        public string VtmclhNumero { get; set; }
        public string VtmclhDppiso { get; set; }
        public string VtmclhDeptos { get; set; }
        public string VtmclhCodfil { get; set; }
        public string VtmclhCodpai { get; set; }
        public string VtmclhCodpos { get; set; }
        public string VtmclhMunicp { get; set; }
        public string VtmclhFletes { get; set; }
        public string VtmclhTelefn { get; set; }
        public string VtmclhNrofax { get; set; }
        public string VtmclhNtelex { get; set; }
        public string VtmclhCndiva { get; set; }
        public string VtmclhTipdoc { get; set; }
        public string VtmclhNrodoc { get; set; }
        public string VtmclhVnddor { get; set; }
        public string VtmclhCobrad { get; set; }
        public string VtmclhJurisd { get; set; }
        public string VtmclhCodzon { get; set; }
        public string VtmclhActivd { get; set; }
        public string VtmclhCatego { get; set; }
        public string VtmclhCndpag { get; set; }
        public string VtmclhCndpre { get; set; }
        public string VtmclhCodcrd { get; set; }
        public string VtmclhGrubon { get; set; }
        public string VtmclhCamion { get; set; }
        public string VtmclhCamalt { get; set; }
        public string VtmclhTracod { get; set; }
        public string VtmclhDirep1 { get; set; }
        public string VtmclhDirep2 { get; set; }
        public string VtmclhDirep3 { get; set; }
        public string VtmclhDirep4 { get; set; }
        public string VtmclhDirep5 { get; set; }
        public string VtmclhHorrec { get; set; }
        public string VtmclhDirent { get; set; }
        public string VtmclhPaient { get; set; }
        public string VtmclhCodent { get; set; }
        public string VtmclhJurent { get; set; }
        public string VtmclhZonent { get; set; }
        public short VtmclhCopivt { get; set; }
        public short VtmclhCopifc { get; set; }
        public short VtmclhCopist { get; set; }
        public string VtmclhTextos { get; set; }
        public string VtmclhTipdo1 { get; set; }
        public string VtmclhNrodo1 { get; set; }
        public string VtmclhTipdo2 { get; set; }
        public string VtmclhNrodo2 { get; set; }
        public string VtmclhTipdo3 { get; set; }
        public string VtmclhNrodo3 { get; set; }
        public string VtmclhTipdo4 { get; set; }
        public string VtmclhNrodo4 { get; set; }
        public string VtmclhTipdo5 { get; set; }
        public string VtmclhNrodo5 { get; set; }
        public string VtmclhDireml { get; set; }
        public string VtmclhSegpro { get; set; }
        public string VtmclhContad { get; set; }
        public string VtmclhEdisub { get; set; }
        public string VtmclhCuenta { get; set; }
        public short? VtmclhMaxitm { get; set; }
        public short? VtmclhDifdia { get; set; }
        public DateTime? VtmclhDifdes { get; set; }
        public DateTime? VtmclhDifhas { get; set; }
        public decimal? VtmclhPerina { get; set; }
        public decimal? VtmclhImpdif { get; set; }
        public string VtmclhEmail { get; set; }
        public string VtmclhCndint { get; set; }
        public string VtmclhDistri { get; set; }
        public string VtmclhDeposi { get; set; }
        public string VtmclhSector { get; set; }
        public string VtmclhNrodis { get; set; }
        public string VtmclhOleole { get; set; }
        public string VtmclhBmpbmp { get; set; }
        public string VtmclhInhibe { get; set; }
        public decimal? VtmclhPrmxpr { get; set; }
        public decimal? VtmclhPrmipr { get; set; }
        public string VtmclhTrafcr { get; set; }
        public string VtmclhCodcof { get; set; }
        public string VtmclhModcpt { get; set; }
        public string VtmclhTipcpt { get; set; }
        public string VtmclhCodcpt { get; set; }
        public string VtmclhLiscli { get; set; }
        public string VtmclhTipopr { get; set; }
        public string VtmclhCodopr { get; set; }
        public string VtmclhModpag { get; set; }
        public string VtmclhTippag { get; set; }
        public string VtmclhMedpag { get; set; }
        public string VtmclhLanexp { get; set; }
        public string VtmclhGenxml { get; set; }
        public string VtmclhGlndes { get; set; }
        public string VtmclhCodexp { get; set; }
        public string VtmclhOblcon { get; set; }
        public string VtmclhDeptra { get; set; }
        public string VtmclhSectra { get; set; }
        public string VtmclhFisjur { get; set; }
        public string VtmclhApell1 { get; set; }
        public string VtmclhApell2 { get; set; }
        public string VtmclhNomb01 { get; set; }
        public string VtmclhNomb02 { get; set; }
        public string UsrVtmclhCodact { get; set; }
        public string UsrVtmclhMpago { get; set; }
        public string UsrVtmclhNro1 { get; set; }
        public string UsrVtmclhNrpis1 { get; set; }
        public string UsrVtmclhDepa1 { get; set; }
        public string UsrVtmclhLocal1 { get; set; }
        public string UsrVtmclhNro2 { get; set; }
        public string UsrVtmclhNrpis2 { get; set; }
        public string UsrVtmclhDepa2 { get; set; }
        public string UsrVtmclhLocal2 { get; set; }
        public decimal? UsrVtmclhCbudia { get; set; }
        public string UsrVtmclhCbutip { get; set; }
        public string UsrVtmclhCbunro { get; set; }
        public string UsrVtmclhCbubco { get; set; }
        public string UsrVtmclhCbusuc { get; set; }
        public string UsrVtmclhSubpo1 { get; set; }
        public string UsrVtmclhMotivo { get; set; }
        public string UsrVtmclhSubpo2 { get; set; }
        public string UsrVtmclhLeyco1 { get; set; }
        public string UsrVtmclhLeyco2 { get; set; }
        public string UsrVtmclhAtentr { get; set; }
        public string UsrVtmclhArchiv { get; set; }
        public string UsrVtmclhIdcust { get; set; }
        public int? UsrVtmclhNroreg { get; set; }
        public DateTime? UsrVtmclhFchimp { get; set; }
        public string UsrVtmclhDircob { get; set; }
        public string UsrVtmclhPaicob { get; set; }
        public string UsrVtmclhCodcob { get; set; }
        public string UsrVtmclhTelcob { get; set; }
        public string UsrVtmclhDirco2 { get; set; }
        public string UsrVtmclhCodpfi { get; set; }
        public string UsrVtmclhCodpen { get; set; }
        public string UsrVtmclhMailfc { get; set; }
        public string UsrVtmclhMailrc { get; set; }
        public string UsrVtmclhEnmail { get; set; }
        public string UsrVtmclhNomant { get; set; }
        public DateTime? UsrVtmclhFecant { get; set; }
        public DateTime? VtmclhFecalt { get; set; }
        public DateTime? VtmclhFecmod { get; set; }
        public string VtmclhUserid { get; set; }
        public string VtmclhUltopr { get; set; }
        public string VtmclhDebaja { get; set; }
        public string VtmclhHormov { get; set; }
        public string VtmclhModule { get; set; }
        public string VtmclhOalias { get; set; }
        //public byte[] VtmclhTstamp { get; set; }
        public string VtmclhLottra { get; set; }
        public string VtmclhLotrec { get; set; }
        public string VtmclhLotori { get; set; }
        public string VtmclhSysver { get; set; }
        public string VtmclhCmpver { get; set; }
        public List<Vtmclc> Contactos { get; set; }
    }
}
