using System;
using System.Collections.Generic;

#nullable disable

namespace APINosis.Entities
{
    public partial class Vtrmvi
    {
        public string Vtrmvi_Modfor { get; set; }
        public string Vtrmvi_Codfor { get; set; }
        public int Vtrmvi_Nrofor { get; set; }
        public int Vtrmvi_Nroitm { get; set; }
        public string Vtrmvi_Debhab { get; set; }
        public string Vtrmvi_Modcpt { get; set; }
        public string Vtrmvi_Tipcpt { get; set; }
        public string Vtrmvi_Codcpt { get; set; }
        public string Vtrmvi_Cuenta { get; set; }
        public decimal? Vtrmvi_Cantid { get; set; }
        public decimal? Vtrmvi_Factor { get; set; }
        public string Vtrmvi_Unimed { get; set; }
        public string Vtrmvi_Tipuni { get; set; }
        public string Vtrmvi_Unifac { get; set; }
        public decimal? Vtrmvi_Facfac { get; set; }
        public decimal? Vtrmvi_Cntfac { get; set; }
        public string Vtrmvi_Unialt { get; set; }
        public decimal? Vtrmvi_Facalt { get; set; }
        public decimal? Vtrmvi_Cntalt { get; set; }
        public string Vtrmvi_Unicon { get; set; }
        public decimal? Vtrmvi_Faccon { get; set; }
        public decimal? Vtrmvi_Cntcon { get; set; }
        public decimal? Vtrmvi_Oldpre { get; set; }
        public decimal? Vtrmvi_Newpre { get; set; }
        public decimal? Vtrmvi_Prenac { get; set; }
        public decimal? Vtrmvi_Impnac { get; set; }
        public decimal? Vtrmvi_Preuss { get; set; }
        public decimal? Vtrmvi_Impuss { get; set; }
        public decimal? Vtrmvi_Preext { get; set; }
        public decimal? Vtrmvi_Impext { get; set; }
        public decimal? Vtrmvi_Pcinac { get; set; }
        public decimal? Vtrmvi_Icinac { get; set; }
        public decimal? Vtrmvi_Pciext { get; set; }
        public decimal? Vtrmvi_Iciext { get; set; }
        public decimal? Vtrmvi_Pciuss { get; set; }
        public decimal? Vtrmvi_Iciuss { get; set; }
        public decimal? Vtrmvi_Impdeb { get; set; }
        public decimal? Vtrmvi_Imphab { get; set; }
        public string Vtrmvi_Modapl { get; set; }
        public string Vtrmvi_Codapl { get; set; }
        public int? Vtrmvi_Nroapl { get; set; }
        public short? Vtrmvi_Cuoapl { get; set; }
        public string Vtrmvi_Textos { get; set; }
        public string Vtrmvi_Tippro { get; set; }
        public string Vtrmvi_Artcod { get; set; }
        public string Vtrmvi_Tipdes { get; set; }
        public string Vtrmvi_Artdes { get; set; }
        public string Vtrmvi_Nserie { get; set; }
        public string Vtrmvi_Ndespa { get; set; }
        public string Vtrmvi_Envase { get; set; }
        public string Vtrmvi_Notros { get; set; }
        public string Vtrmvi_Tserie { get; set; }
        public string Vtrmvi_Tdespa { get; set; }
        public string Vtrmvi_Tenvas { get; set; }
        public string Vtrmvi_Totros { get; set; }
        public string Vtrmvi_Deposi { get; set; }
        public string Vtrmvi_Sector { get; set; }
        public string Vtrmvi_Modori { get; set; }
        public string Vtrmvi_Codori { get; set; }
        public int? Vtrmvi_Nroori { get; set; }
        public int? Vtrmvi_Itmori { get; set; }
        public string Vtrmvi_Expori { get; set; }
        public decimal? Vtrmvi_Pctbf1 { get; set; }
        public decimal? Vtrmvi_Pctbf2 { get; set; }
        public decimal? Vtrmvi_Pctbf3 { get; set; }
        public decimal? Vtrmvi_Pctbf4 { get; set; }
        public decimal? Vtrmvi_Pctbf5 { get; set; }
        public decimal? Vtrmvi_Pctbf6 { get; set; }
        public decimal? Vtrmvi_Pctbf7 { get; set; }
        public decimal? Vtrmvi_Pctbf8 { get; set; }
        public decimal? Vtrmvi_Pctbf9 { get; set; }
        public decimal? Vtrmvi_Pctbfn { get; set; }
        public decimal? Vtrmvi_Ussdeb { get; set; }
        public decimal? Vtrmvi_Usshab { get; set; }
        public decimal? Vtrmvi_Extdeb { get; set; }
        public decimal? Vtrmvi_Exthab { get; set; }
        public string Vtrmvi_Codcon { get; set; }
        public string Vtrmvi_Nrocon { get; set; }
        public short? Vtrmvi_Nroext { get; set; }
        public int? Vtrmvi_Itmcon { get; set; }
        public decimal? Vtrmvi_Impori { get; set; }
        public string Vtrmvi_Nfecha { get; set; }
        public string Vtrmvi_Natrib { get; set; }
        public string Vtrmvi_Nubica { get; set; }
        public string Vtrmvi_Nestan { get; set; }
        public string Vtrmvi_Tfecha { get; set; }
        public string Vtrmvi_Tatrib { get; set; }
        public string Vtrmvi_Tubica { get; set; }
        public string Vtrmvi_Testan { get; set; }
        public string Vtrmvi_Clamov { get; set; }
        public decimal? Vtrmvi_Impsec { get; set; }
        public decimal? Vtrmvi_Secdeb { get; set; }
        public decimal? Vtrmvi_Sechab { get; set; }
        public string Vtrmvi_Tipopr { get; set; }
        public string Vtrmvi_Codopr { get; set; }
        public decimal? Vtrmvi_Tasa01 { get; set; }
        public decimal? Vtrmvi_Tasa02 { get; set; }
        public decimal? Vtrmvi_Tasa03 { get; set; }
        public decimal? Vtrmvi_Tasa04 { get; set; }
        public decimal? Vtrmvi_Tasa05 { get; set; }
        public decimal? Vtrmvi_Tasa06 { get; set; }
        public decimal? Vtrmvi_Impu01 { get; set; }
        public decimal? Vtrmvi_Impu02 { get; set; }
        public decimal? Vtrmvi_Impu03 { get; set; }
        public decimal? Vtrmvi_Impu04 { get; set; }
        public decimal? Vtrmvi_Impu05 { get; set; }
        public decimal? Vtrmvi_Impu06 { get; set; }
        public string Vtrmvi_Codemp { get; set; }
        public string Vtrmvi_Empori { get; set; }
        public string Vtrmvi_Empapl { get; set; }
        public string Vtrmvi_Empcon { get; set; }
        public short? Vtrmvi_Anovig { get; set; }
        public string Vtrmvi_Codcur { get; set; }
        public string Vtrmvi_Codniv { get; set; }
        public string Vtrmvi_Codano { get; set; }
        public decimal? Vtrmvi_Intnoi { get; set; }
        public string Vtrmvi_Codpro { get; set; }
        public string Vtrmvi_Despro { get; set; }
    }
}
